zuul:
  prefix: /api

  routes:
    realtor:
        path: /realtor-service/**
        serviceId: realtor-service
    client:
        path: /client-service/**
        serviceId: client-service
  ignored-services: '*'